INSERT INTO products (id, name, price, currency, category, stock_quantity, image_thumb, image_mobile, image_tablet, image_desktop) VALUES
('1', 'Waffle with Berries', 6.50, 'USD', 'Waffle', 100,
 'https://orderfoodonline.deno.dev/public/images/image-waffle-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-waffle-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-waffle-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-waffle-desktop.jpg'),
('2', 'Vanilla Bean Crème Brûlée', 7.00, 'USD', 'Crème Brûlée', 100,
 'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-creme-brulee-desktop.jpg'),
('3', 'Macaron Mix of Five', 8.00, 'USD', 'Macaron', 100,
 'https://orderfoodonline.deno.dev/public/images/image-macaron-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-macaron-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-macaron-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-macaron-desktop.jpg'),
('4', 'Classic Tiramisu', 5.50, 'USD', 'Tiramisu', 100,
 'https://orderfoodonline.deno.dev/public/images/image-tiramisu-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-tiramisu-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-tiramisu-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-tiramisu-desktop.jpg'),
('5', 'Pistachio Baklava', 4.00, 'USD', 'Baklava', 100,
 'https://orderfoodonline.deno.dev/public/images/image-baklava-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-baklava-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-baklava-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-baklava-desktop.jpg'),
('6', 'Lemon Meringue Pie', 5.00, 'USD', 'Pie', 100,
 'https://orderfoodonline.deno.dev/public/images/image-meringue-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-meringue-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-meringue-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-meringue-desktop.jpg'),
('7', 'Red Velvet Cake', 4.50, 'USD', 'Cake', 100,
 'https://orderfoodonline.deno.dev/public/images/image-cake-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-cake-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-cake-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-cake-desktop.jpg'),
('8', 'Salted Caramel Brownie', 4.50, 'USD', 'Brownie', 100,
 'https://orderfoodonline.deno.dev/public/images/image-brownie-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-brownie-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-brownie-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-brownie-desktop.jpg'),
('9', 'Vanilla Panna Cotta', 6.50, 'USD', 'Panna Cotta', 100,
 'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-thumbnail.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-mobile.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-tablet.jpg',
 'https://orderfoodonline.deno.dev/public/images/image-panna-cotta-desktop.jpg')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    currency = EXCLUDED.currency,
    category = EXCLUDED.category,
    stock_quantity = EXCLUDED.stock_quantity,
    image_thumb = EXCLUDED.image_thumb,
    image_mobile = EXCLUDED.image_mobile,
    image_tablet = EXCLUDED.image_tablet,
    image_desktop = EXCLUDED.image_desktop;

-- Seed well-known promo codes with their discount percentages
INSERT INTO promo_codes (code, file_index, discount_percentage) VALUES
    ('HAPPYHRS', 1, 18.00),
    ('HAPPYHRS', 2, 18.00),
    ('BUYGETONE', 1, 0.00),
    ('BUYGETONE', 2, 0.00)
ON CONFLICT (code, file_index) DO UPDATE SET
    discount_percentage = EXCLUDED.discount_percentage;
